services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - BOT_CLIENT_ID=123456789012345678
      - BOT_SECRET=your_bot_secret_here
      - MARIADB_HOST=192.168.xxx.xxx
      - MARIADB_PORT=3306
      - MARIADB_USER=your_db_user
      - MARIADB_PASSWORD=your_db_password
      - MARIADB_DATABASE=your_db_name
      - DATABASE_URL=mysql://your_db_user:your_db_password@192.168.xxx.xxx:3306/your_db_name

      - TRELLO_KEY=your_trello_key
      - TRELLO_TOKEN=your_trello_token
